obj-$(CONFIG_USB_WPAN_HCD)	+= ozwpan/
obj-$(CONFIG_TEGRA_HTS_GTE)     += platform/tegra/gte/
obj-$(CONFIG_TEGRA_GTE_TEST)	+= platform/tegra/gte_test/
obj-$(CONFIG_DUMMY_MEMORY_CARVEOUT) += platform/tegra/dummy_carveout/

