#!/bin/bash

export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
export PATH=$PATH:/opt/gcc-linaro-4.9-2014.11-x86_64_aarch64-linux-gnu/bin/

#make clean

#make meson64_defconfig

#make -j4 Image modules gxbb_p200_2G.dtb

make menuconfig
