ccflags-y += 			-I$(srctree.nvidia)/include
obj-y +=			nvlink-core.o
obj-y +=			t19x-nvlink-endpt.o
obj-$(CONFIG_DEBUG_FS) +=	t19x-nvlink-endpt-debugfs.o
obj-y +=			t19x-nvlink-endpt-ioctl.o
obj-y +=			t19x-nvlink-endpt-isr.o
obj-y +=			t19x-nvlink-endpt-link.o
obj-y +=			t19x-nvlink-endpt-minion.o
