obj-$(CONFIG_MODS) += mods/
obj-$(CONFIG_NVS) += nvs/
obj-$(CONFIG_NVS_AON_SHUB) += nvs-aonsh/
obj-$(CONFIG_TEGRA_PROFILER) += tegra-profiler/

obj-$(CONFIG_NVS_DFSH) += nvs-dfsh/
obj-$(CONFIG_SAF775x_HWDEP) += saf775x/
obj-$(CONFIG_SAF36XX_HWDEP) += saf775x/
obj-$(CONFIG_BLUEDROID_PM)      += bluedroid_pm.o
obj-$(CONFIG_SENSORS_NCT1008)	+= nct1008.o
obj-$(CONFIG_SENSORS_PEX9749)	+= pex9749.o
obj-$(CONFIG_TEGRA_CPC)		+= tegra_cpc.o
obj-$(CONFIG_THERM_EST)		+= therm_est.o
obj-$(CONFIG_FAN_THERM_EST)	+= therm_fan_est.o
obj-$(CONFIG_EQOS_APE_HWDEP) += eqos_ape/
obj-$(CONFIG_TEGRA_SKIN)	+= tegra-skin.o
obj-$(CONFIG_TEGRA186_AHC) += tegra186-ahc/
obj-$(CONFIG_EVENTLIB)		+= eventlib/

ifdef CONFIG_ARCH_TEGRA_19x_SOC

obj-$(CONFIG_TEGRA_PCIE_EP_MEM)	+= tegra-pcie-ep-mem.o

endif
