subdir-ccflags-y			+= -Werror

obj-$(CONFIG_DEBUG_FS)			+= bpmp_t210.o
obj-$(CONFIG_DEBUG_FS)			+= fwdebug.o
obj-y					+= nv_bpmp.o
obj-y					+= bpmp_tty.o
obj-y					+= mail.o
obj-y					+= mail_t186.o
obj-y					+= mail_t210.o
obj-y					+= mailman.o

GCOV_PROFILE				:= y
