obj-$(CONFIG_TOUCHSCREEN_NVIDIA_ATMEL_MXT) += atmel_mxt_ts_nv.o
obj-$(CONFIG_TOUCHSCREEN_RM31080A)	   += rm31080a_ts.o rm31080a_ctrl.o
obj-$(CONFIG_TOUCHSCREEN_LR388K7)	   += lr388k7_ts.o
obj-$(CONFIG_TOUCHSCREEN_EXC80)		   += exc80_ts.o
obj-$(CONFIG_TOUCHSCREEN_EXC80_USB)	   += exc80_ts_usb.o