ccflags-y += -I$(srctree)/drivers/hid

obj-$(CONFIG_HID_SHIELD_BLAKE) += hid-nvidia-blake.o
obj-$(CONFIG_HID_SHIELD_REMOTE) += hid-jarvis-remote.o
hid-jarvis-remote-objs := hid-atv-jarvis.o sbcdec.o
obj-$(CONFIG_HID_NVIDIA_STAND)	+= hid-raven.o
