#
# nvdumper code.
#

GCOV_PROFILE := y

obj-${CONFIG_TEGRA_NVDUMPER}            += nvdumper.o
obj-${CONFIG_TEGRA_NVDUMPER}            += nvdumper_regdump.o
obj-${CONFIG_TEGRA_NVDUMPER}            += nvdumper-footprint.o
obj-${CONFIG_TEGRA_NVDUMPER}            += nvdumper_config.o
obj-${CONFIG_TEGRA_NVDUMPER}            += nvdumper_reg_tegra.o
