GCOV_PROFILE := y

#subdir-ccflags-y := -Werror
#
# Makefile for the video capture/playback device drivers.
#
obj-$(CONFIG_VIDEO_CAMERA)	+= camera/
obj-$(CONFIG_VIDEO_TEGRA_VI)	+= vi/
obj-$(CONFIG_VIDEO_CAMERA)	+= regmap_util.o
obj-$(CONFIG_VIDEO_TEGRA_VI_TPG) += tpg/
obj-$(CONFIG_TEGRA_MIPI_CAL)	+= mipical/
obj-$(CONFIG_VIDEO_ISC)		+= isc/
