#
# Makefile for Hypervisor interface
#

obj-$(CONFIG_TEGRA_HV_PM_CTL)		+= tegra_hv_pm_ctl.o

obj-$(CONFIG_TEGRA_HV_MANAGER)		+= tegra_hv.o ivc-cdev.o hvc_sysfs.o
obj-$(CONFIG_TEGRA_HV_MANAGER)		+= userspace_ivc_mempool.o

