obj-$(CONFIG_TEGRA_CAMERA_PLATFORM) += camera/
obj-$(CONFIG_TEGRA_GRHOST) += host/
obj-$(CONFIG_TEGRA_NVMAP) += nvmap/
obj-$(CONFIG_TEGRA_GR_VIRTUALIZATION) += virt/

GCOV_PROFILE := y
#subdir-ccflags-y := -Werror

obj-$(CONFIG_TEGRA_DC) += dc/
obj-$(CONFIG_FB_TEGRA) += fb.o
