#
# Makefile for industrial I/O light sensor drivers
#

# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_NVS_BH1730FVC)	+= nvs_bh1730fvc.o
obj-$(CONFIG_NVS_CM3217)	+= nvs_cm3217.o
obj-$(CONFIG_NVS_CM3218)	+= nvs_cm3218.o
obj-$(CONFIG_NVS_ISL2902X)	+= nvs_isl2902x.o
obj-$(CONFIG_NVS_JSA1127)	+= nvs_jsa1127.o
obj-$(CONFIG_NVS_LTR659)	+= nvs_ltr659.o
obj-$(CONFIG_NVS_MAX4400X)	+= nvs_max4400x.o
obj-$(CONFIG_NVS_VEML6030)	+= nvs_veml6030.o

