ccflags-y += -Werror
obj-$(CONFIG_TEGRA21X_WATCHDOG) += tegra_wdt_t21x.o
obj-$(CONFIG_TEGRA18X_WATCHDOG) += tegra_wdt_t18x.o
obj-$(CONFIG_TEGRA_HV_WATCHDOG) += tegra_hv_wdt.o
obj-$(CONFIG_SOFT_PLATFORM_WATCHDOG) += softdog_platform.o
