ccflags-$(CONFIG_SCSI_UFSHCD_TEGRA) += -I$(srctree)/drivers/scsi/ufs
ccflags-$(CONFIG_SCSI_UFSHCD_TEGRA) += -I$(srctree)
ccflags-$(CONFIG_SCSI_UFSHCD_TEGRA) += -I$(srctree.nvidia)

obj-$(CONFIG_SCSI_UFSHCD_TEGRA) += ufs-tegra.o ufs-provision.o
