# Copyright (c) 2017-2018, NVIDIA CORPORATION.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

subdir-ccflags-y += -Werror

obj-$(CONFIG_RTK_BTUSB)         += bluetooth/realtek/
obj-$(CONFIG_NVPMODEL_EMC)      += nvpmodel/
obj-$(CONFIG_TEGRA_NVLINK)	+= nvlink/
obj-$(CONFIG_NVPPS)		+= nvpps/
obj-$(CONFIG_THERMAL)  += thermal/
obj-$(CONFIG_TRUSTY)		+= trusty/
obj-$(CONFIG_TEGRA_HV_MANAGER)	+= virt/tegra/
obj-y	+= gpu/

