obj-$(CONFIG_TEGRA_COMBINED_UART) += tegra-combined-uart.o
obj-$(CONFIG_TEGRA_COMBINED_UART) += tegra-combined-uart-early.o
obj-$(CONFIG_TEGRA_HV_COMM)	+= tegra_hv_comm.o
obj-$(CONFIG_SERIAL_TEGRA) += serial-tegra-nohw.o
